import { Component, VERSION } from '@angular/core';
function log(target, name, descriptor){
  console.log(target, name, descriptor)
  const original = descriptor.value
  
  descriptor.value=function(...args){
    console.log("Arguments ",args," were passed in this fuction")
    const result = original.apply(this, args)
    console.log("The result of the function is ", result)
    return new className(...args)
  }
  return descriptor
}

@log
class myExampleClass{
constructor(arg1,arg2){
  console.log("Constructor fired!")
}
}

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})

export class AppComponent  {
  name = 'Svarti ' + VERSION.major;
constructor(){
  console.log("This statement was generated by the constructor", this.aSimpleMethod(5,2))
}

@log
aSimpleMethod(a,b)
{return a*b}
}
